### ISSUE TITLE
Installation error 

### ISSUE THREAD

**Issue by gustavengstrom** [jrief/django-formset#102]
After following the installation instructions in the docs. I recieved a: 

ModuleNotFoundError: No module named 'phonenumbers' 

which was caused by line two in:

formset/templatetags/phonenumber.py

I resolved this by:
pip install django-phonenumbers

This is a dependency this should be mentioned in the docs.

**Comment by jrief** [comment]
> This is a dependency this should be mentioned in the docs.

It is:
https://django-formset.fly.dev/phone-number-field/#rendering-phone-numbers

you need `phonenumbers` not `django-phonenumbers`
