### ISSUE TITLE
Missing csrf token FormCollection

### ISSUE THREAD

**Issue by Tobi-De** [jrief/django-formset#11]
I'm getting a ` (CSRF token missing.)` when I submit a form collection.
here is my setup

```html
{% extends "base.html" %}
{% load static formsetify %}

{% block content %}
  <django-formset endpoint="{{ request.path }}">
    {% with dummy=csrf_token.0 %}{% endwith %}
    {{ form_collection }}
    <div class="">
      <button type="button"
              click="disable -> submit -> proceed !~ scrollToError"
              class="btn btn-primary">Submit<span
        class="ms-2 dj-button-decorator"><i class="dj-icon">{% include "formset/icons/send.svg" %}</i></span></button>
      <button type="button" click="reset" class="ms-2 btn btn-warning">Reset to initial<span
        class="ms-2 dj-button-decorator"><i class="dj-icon">{% include "formset/icons/backspace.svg" %}</i></button>
    </div>
  </django-formset>
{% endblock content %}

```

```python
# forms.py
class WorkflowFormCollection(FormCollection):
    default_renderer = FormRenderer()
    workflow = WorkflowForm()
    activities = ActivityFormCollection(
        min_siblings=1, max_siblings=10, extra_siblings=1
    )

# views.py

from formset.views import FormCollectionView

from .forms import WorkflowFormCollection


class CreateWorkflowView(FormCollectionView):
    collection_class = WorkflowFormCollection
    template_name = "workflows/create.html"

    def form_collection_valid(self, form_collection: WorkflowFormCollection):
        print(form_collection)
        return JsonResponse({'success_url': self.get_success_url()})


```

When running locally your bootstap 11-contactlist demo does the same things, the form is submitted with a `crsf token missing` printout in the console.

**Comment by jrief** [comment]
This is strange because `{% with dummy=csrf_token.0 %}{% endwith %}` should set the cookie.

Could you please tell me the browser and version you're using. It might be the same problem (and fix) as described here: https://github.com/jrief/django-admin-sortable2/issues/303

**Comment by Tobi-De** [comment]
I'm using the latest official chrome build: 103.0.5060.134 
I also tried on the latest firefox version: 102.0.1
Same error: Forbidden (CSRF token missing.)
I checked in my browser's developer tools network tab and there is a csrftoken cookie in the header of my post request.
I am probably doing something wrong here

**Comment by jrief** [comment]
Thanks for testing.

I never experienced this problem myself. Please test my pull request #13 which fixes this.

Remember to build the client code, before using this branch.

**Comment by Tobi-De** [comment]
Ok will try it

**Comment by jrief** [comment]
@Tobi-De Have you been able to test it? I'd like to merge that pull request.

**Comment by Tobi-De** [comment]
> @Tobi-De Have you been able to test it? I'd like to merge that pull request.

Sorry for the late reply, I just tested it, this PR solves my issues, great job sir.

**Comment by Tobi-De** [comment]
This has nothing to do with this particular issue, but I found a typo in the name of one of your classes. I didn't want to create a new issue just for that.

```python
# formset/views.py
class IncompleSelectResponseMixin: # Incomplete
    ...

```
Nothing dramatic really, I intended to change it myself but I wasn't able to configure the test environment properly yet and Ididn't want to break anything.

**Comment by jrief** [comment]
Fixed that typo.
