### ISSUE TITLE
Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/html". Strict MIME type checking is enforced for module scripts per HTML spec.

### ISSUE THREAD

**Issue by parice02** [jrief/django-formset#116]
Hello!
I get this error message when I go into production. I followed the installation steps correctly (I think). But the browser keeps giving me this error.

I've just migrated to 1.3.8
This is the first time I've encountered this error since I started using this library. I've tried most of the solutions on stackoverflow without success.

**Comment by jrief** [comment]
Your browser probably attempts to load one of the JavaScript modules during runtime. That script might be named `chunk-Z3HLVUBI.js` or something similar.

Could you please open the devtools of your browser and open the network tab. Then load the page. In your network activity tab, you should see many JS files loading. Check their response headers. If `Content-Type` is not `application/javascript` your webserver presumably is misconfigured.

**Comment by parice02** [comment]
When I look in the DevTools, I notice that django-formset.js is loaded with the Content-Type text/html.
![Screenshot from 2024-03-05 17-20-24](https://github.com/jrief/django-formset/assets/36199587/8bdf1457-1bd0-43fc-9149-3325b2667204)

**Comment by jrief** [comment]
> When I look in the DevTools, I notice that django-formset.js is loaded with the Content-Type text/html.

well, then you have the culprit.
