### ISSUE TITLE
Still have the problem with new release 1.3.9. It happened when I use selectize widget and when I use active search in the widget and it tries to get answer from backend to get new list of options.

### ISSUE THREAD

**Issue by amikphoto** [jrief/django-formset#125]
Still have the problem with new release 1.3.9. It happened when I use selectize widget and when I use active search in the widget and it tries to get answer from backend to get new list of options. 

The problem appears in:

class FormCollection(BaseFormCollection, metaclass=FormCollectionMeta):
    """
    Base class for a collection of forms. Attributes of this class which inherit from
    `django.forms.forms.BaseForm` are managed by this class.
    """
    def get_field(self, field_path):
        path = field_path.split('.', 1)
        key, path = path
        return self.declared_holders[key].get_field(path)

![image](https://github.com/jrief/django-formset/assets/36606543/c8ac07d4-4050-4859-afb1-7c3d3fe2ff9b)

self.declared_holders[key].get_field(path) return KeyError:'0'

_Originally posted by @amikphoto in https://github.com/jrief/django-formset/issues/122#issuecomment-2027969408_

**Comment by amikphoto** [comment]
I'm sorry to disturb you, but could you tell me is there a problem with selectize widget when we are using it in form collections or it's only my  problem? :)

**Comment by jrief** [comment]
Is there a setup where I can reproduce this?

**Comment by amikphoto** [comment]
you could add selectize widget to your test application in any form collection. For best expirience you should set max_prefetch_choices to 2 (from 250). It helps to find problem with working with backend.

**Comment by jrief** [comment]
This has been fixed now and will work in version 1.3.10

**Comment by amikphoto** [comment]
Thank you very much! Yes, the problem is solved. Going to see next one :)

**Comment by jrief** [comment]
Thanks for reporting. Understanding other's use-cases help me to improve the stability of the project.
