### ISSUE TITLE
BooleanField shows label twice

### ISSUE THREAD

**Issue by lsmoker** [jrief/django-formset#128]
In 1.3.9, a BooleanField named `checkbox` will show "Checkbox: Checkbox" before the input control. Using the bootstrap FormRenderer.

**Comment by jrief** [comment]
Confirmed. Thanks for reporting.

**Comment by jrief** [comment]
This regression has been added in aa0be005a987bd354d54afff5127ac3aca923b7e and was part of release 1.3.8 and 1.3.9. Will be fixed in 1.3.10. Sorry for the inconvenience.
