### ISSUE TITLE
Style problem in Selectize widget.

### ISSUE THREAD

**Issue by amikphoto** [jrief/django-formset#132]
The problem appears when resizing the browser window. The size of the input window does not change as the window size changes
I fixed it in browser adding class to the div (div class="ts-control" style="width: 100%"). But as I understand this div was created with JS, so I can't correct it. Could you fix it?

**Comment by jrief** [comment]
> The size of the input window does not change as the window size changes

well spotted. This is because django-formset pilfers the styles from the original `<select>`-element and applies them to the web component implementing the functionality. I will try to add an event listener and recompute the styles.

Thanks for reporting.

**Comment by jrief** [comment]
This should be fixed now in branch `develop` and `releases/1.4`.

Please test and confirm. I then will release version 1.4.1 and 1.3.11
