### ISSUE TITLE
Submit button shows bummer symbol after okay symbol.

### ISSUE THREAD

**Issue by oisy92** [jrief/django-formset#136]
**Current Behavior:**

After a successful post request, the submit button shows okay symbol, but shortly after, it shows the bummer symbol.

**Desired Behavior:**

In the event of successful post request, the submit button should show okay symbol, without displaying bummer symbol afterwards.

**How to Reproduce Current Behavior:**

1 - Go to the form in [Action Queues](https://django-formset.fly.dev/buttons/#action-queues) documentation.
2 - Set network throttle to slow 3G (This is not required, but it helps to spot the bummer symbol clearer).
3 - Check valid box and click Submit.

**Comment by jrief** [comment]
Well spotted. Thanks for reporting.

**Comment by jrief** [comment]
Please recheck using the latest commit from branch `release/1.4`.

**Comment by oisy92** [comment]
Resolved. Thanks Jacob!
