### ISSUE TITLE
The size of the input window does not change as the window size changes

### ISSUE THREAD

**Issue by amikphoto** [jrief/django-formset#137]
Still have the problem in 1.4 release

> The size of the input window does not change as the window size changes

well spotted. This is because django-formset pilfers the styles from the original `<select>`-element and applies them to the web component implementing the functionality. I will try to add an event listener and recompute the styles.

Thanks for reporting.

_Originally posted by @jrief in https://github.com/jrief/django-formset/issues/132#issuecomment-2053603974_

**Comment by jrief** [comment]
Duplicate of #132 

This bug has not been fixed yet and is not mentioned on the Changelog.
