### ISSUE TITLE
FormCollections with RichtextArea not working

### ISSUE THREAD

**Issue by codematsing** [jrief/django-formset#142]
Hi! Reporting another issue: https://github.com/codematsing/django-formset-debug/commit/cf4e7b4d93febfbab31b315d15881b4b61932746

# Execution:

Minor introduction of form field with RichtextArea on Gallery Form Collection for demonstration

# Expectation:

* Access http://localhost:8001/bootstrap/gallerycollection
* Click add activity
* Should be able to add a new Image Form
* Click Submit
* Should submit

# Actual Results:

* Nothing happens when clicking other buttons

# Notes:

* I tried to debug using chrome dev-tools and console logs but I couldn't find any error logs to point me to any issues. It's as if buttons just don't respond at all

**Comment by jrief** [comment]
Well spotted. I was able to reproduce this and fixed it using the monolithic build. I still have to check why it doesn't work in the default build. It seems as if the RichtextArea never fires a connected event. I stay tuned.

**Comment by jrief** [comment]
@codematsing please try to proceed with the monolithic build until I found a solution for this problem. Feedback is welcomed.

**Comment by jrief** [comment]
This issue has been fixed in version 1.5. @codematsing Please check out branch https://github.com/jrief/django-formset/tree/releases/1.5 and try if it works form you.
