### ISSUE TITLE
Selectize with 'dynamic' choices, without model

### ISSUE THREAD

**Issue by tobhv** [jrief/django-formset#144]
Hello,

selectize looks good. documentation mentions how to create a dynamic choicefield: https://django-formset.fly.dev/selectize/#usage-with-dynamic-number-of-choices
How about nonmodel based dynamic choices ?

something like:
```
    group = DynamicChoiceField(
        label='groups of my third party system',
        widget=Selectize,
        choices=list_groups(),
        required=False
    )```

or are there any other options to reload the static ChoiceField somehow ?
(the choicefield already works with the list_groups() method. it;s just not dynamic / run again when i revisit the form unless the app gets restarted.

thanks!

**Comment by tobhv** [comment]
hm. answer to my own question:
```
    def __init__(self, *args, **kwargs):
        super(MyUserForm, self).__init__(*args, **kwargs)
        self.fields['group'].choices = list_groups()
```
issue solved..

**Comment by jrief** [comment]
A somehow cleaner way to solve this, is to create your own version of `IncompleteSelectResponseMixin`. Here you fetch data from any other source. However, this in my opinion only makes sense if you have a non-ORM based database, such as Redis or MongoDB for instance.
