### ISSUE TITLE
Getting a 404   from <script type="module" src="{% static 'formset/js/django-formset.min.js' %}"></script>

### ISSUE THREAD

**Issue by onorbumbum** [jrief/django-formset#27]
Hi,
Thank you for an awesome package. This feels like it should be the default way to deal with forms.

I was trying to test it on a project after reading docs, and got a 404 when I tried to load 
<script type="module" src="{% static 'formset/js/django-formset.min.js' %}"></script>

I checked the source and couldn't find the .min.js file, there was however a django-formset.js file that seems like it is minified.
I changed it to:
<script type="module" src="{% static 'formset/js/django-formset.js' %}"></script> and the error is gone.

**Comment by jrief** [comment]
Ups, thanks for reporting!
