### ISSUE TITLE
Django-formset - i am facing the issue - Uncaught (in promise) SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON

### ISSUE THREAD

**Issue by sasikumar1978k** [jrief/django-formset#28]
i am facing the following error in my modelchoice control change event 

Uncaught (in promise) SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON

MY CODE

my model
class Places(models.Model):
    placename = models.CharField(max_length=50,unique=True)
    blockname = models.CharField(max_length=50)
    pincode = models.CharField(max_length=6)
    TALUKNAME = models.CharField(max_length=50)
    rev_dist = models.ForeignKey(REVDISTDET, on_delete=models.CASCADE, verbose_name='REVENUE DISTRICT',default='',null=True, )
    edn_dist = models.ForeignKey(EDNDISTDET, on_delete=models.CASCADE, verbose_name='REVENUE DISTRICT',default='',null=True, )
    
    def __str__(self):
        return self.placename

    class Meta:
        ordering = ('placename',)

class Officedet(models.Model):

    PlaceArea=[('1','Rural'),('2','Urban'),('3', 'NOT APPLICABLE'), ]
    YesNo=[('Y','YES'),('N','NO'),('NA', 'NOT APPLICABLE'),]
    office_type_choice = [
        ('SCHOOL','SCHOOL'),
        ('ADMIN','ADMIN'),

    ]
    office_code = models.CharField(max_length=15,unique=True)
    office_name = models.CharField(max_length=150)
    office_address = models.CharField(max_length=250, verbose_name='Address')
    office_area = models.CharField(max_length=10,choices = PlaceArea,verbose_name='Area Rural/Urban')
    phone_regex = RegexValidator(regex=r'^[789]\d{9}$', message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.")
    office_phone = models.CharField(max_length=10,validators=[phone_regex])
    office_head_name = models.CharField(max_length=50,verbose_name='Head Name')
    office_head_phone1 = models.CharField(max_length=10,validators=[phone_regex],verbose_name='Office Head Contact Number')
    office_head_phone2 = models.CharField(max_length=10,validators=[phone_regex],verbose_name='Office Head Whatsapp Number')
    office_mail = models.EmailField(max_length=50,unique=True)
    office_place = models.ForeignKey('Places', on_delete=models.CASCADE)

my form
class OfficedetForm(forms.ModelForm):
    
    office_logo = fields.FileField(
        label="Office Logo",
        widget=UploadedFileInput,
        required=True,
    )

    office_gender_type = forms.ModelChoiceField(
        queryset=OFFICE_GENDER_TYPE_CHOICE.objects.all(),
        widget=Selectize(
            
            placeholder="Choose Gender",
        ),
    )

    office_mgnt_type = forms.ModelChoiceField(
        queryset=OFFICE_MGNT_TYPE_CHOICE.objects.all(),
        widget=Selectize(
            
            placeholder="Choose Management",
        ),
    )

    office_class_level = forms.ModelChoiceField(
        queryset=OfficeClassLevel.objects.all(),
        widget=Selectize(
            
            placeholder="Choose Class Level",
        ),
    )

    office_place = forms.ModelChoiceField(
        queryset=Places.objects.all(),
        widget=Selectize(
            search_lookup='placename__icontains',
            placeholder="Choose Place",
            
        ),
    )

    office_type = forms.ChoiceField(
        choices=[ ('SCHOOL','SCHOOL'),
        ('ADMIN','ADMIN'),],
        widget=Selectize,
    )

    default_renderer = FormRenderer(
        form_css_classes='row',
        field_css_classes={
            '*': 'mb-2 col-12', 
            "office_code": 'mb-2 col-2', 
            "office_name": 'mb-2 col-4',
            "office_mail": 'mb-2 col-3',
            "office_place": 'mb-2 col-3',
             '*': 'mb-2 col-12', 
            "office_gender_type": 'mb-2 col-3', 
            "office_mgnt_type": 'mb-2 col-3',
            "office_class_level": 'mb-2 col-3',
            "office_type": 'mb-2 col-3',

             '*': 'mb-2 col-12', 
            "office_tanno": 'mb-2 col-4', 
            "office_udisecode": 'mb-2 col-4', 
            "office_logo": 'mb-2 col-4', 

            }
            )
    class Meta:
        model = Officedet
        fields = ["office_code",
"office_name",
"office_mail",
"office_place",
"office_gender_type",
"office_mgnt_type",
"office_class_level",
"office_type",
'office_tanno',
'office_udisecode',
"office_logo",
]
        
My view
class OfficeDetailCreateView(AdminUserTypeAuthMixin,FileUploadMixin, FormViewMixin, LoginRequiredMixin, CreateView):
    model = Officedet
    template_name = 'home/crud/crud_template.html'
    form_class = OfficedetForm
    success_url = reverse_lazy('office_list_view')  # or whatever makes sense
    extra_context = {
        'pagetitle':'Office Creation'
        }
my template
{% extends "layouts/masterpage-formset.html" %}
{% block pagecontent %}
{% load render_form from formsetify %}
<django-formset endpoint="{{ request.path }}" csrf-token="{{ csrf_token }}">
  {% render_form form %}

  
  <div class="{{ button_css_classes }}">
    <button type="button" click="disable -> confirm('Do want to Submit ?') -> spinner -> submit -> okay(500) -> proceed" auto-disable="{{ auto_disable|yesno:'true,false' }}" class="btn btn-primary">Submit<span class="ms-2 dj-button-decorator"><i class="bi bi-send"></i></span></button>
    <button type="button" click="reset" class="ms-2 btn btn-warning">Reset</button>
    <button click="proceed('/office_list_view/')" class="btn btn-info">Back to list</button>
   
</div>
</django-formset>
{% endblock pagecontent %}

**Comment by jrief** [comment]
seems that you're interpreting HTML as JSON.

A bug report like this, without any context is quite useless for me.

**Comment by codematsing** [comment]
I'm facing the same issue.

version: 1.0.1

```
# forms.py
class ScholarshipForm(forms.ModelForm):
    donor = forms.ModelChoiceField(
        queryset=Donor.objects.all(),
        )
    fund_account = forms.ModelChoiceField(
        queryset=FundAccount.objects.all(),
        widget=Selectize(
            filter_by={'donor':'donor__id'},
            )
        )
    class Meta:
        model = Scholarship
        fields = ['name']
```

Error when placing input in donor field in form will cause this issue:
![image](https://github.com/jrief/django-formset/assets/83852662/48cbe696-d1e2-486f-b04a-e9f922a28937)

![image](https://github.com/jrief/django-formset/assets/83852662/23add9fd-a2ad-473e-bd99-9309202baa84)

Seems that the js script is reading the whole html document rather than it's capturing json data

**Comment by jrief** [comment]
why didn't you use widget `Selectize` for field donor?

**Comment by codematsing** [comment]
I found the issue here to be from my source code

If ever someone would encounter this problem, please ensure that the view you are inheriting also inherits `IncompleteSelectResponseMixin` in formset.views

since in my sourcecode I did this implementation:
```python
from formset.views import FormViewMixin
from .forms import CreateForm
class CreateView(..., FormViewMixin, CreateView):
    form_class = CreateForm
```

It was not able to properly process the form using the IncompleteResponseMixin.

A question for @jrief, is it possible for FormViewMixin to inherit IncompleteResponseMixin by default? This could potentially avoid the same case for other developers. I'm just not sure if there will be conflicts or implications for doing so.

Thanks you still for your assistance!

**Comment by jrief** [comment]
> A question for @jrief, is it possible for FormViewMixin to inherit IncompleteSelectResponseMixin by default? This could potentially avoid the same case for other developers. I'm just not sure if there will be conflicts or implications for doing so.

`IncompleteSelectResponseMixin` is only required, if you're using the `Selectize` and `DualSelector` widget **with** asynchronous loading. Not everyone needs that and therefor I prefer to not add another moving part.
