### ISSUE TITLE
Developer instructions out of date

### ISSUE THREAD

**Issue by agseaton** [jrief/django-formset#36]
The developer set up instructions seem to be out of date ([here](https://django-formset.readthedocs.io/en/latest/development.html)).

Currently, it lists the following commands:
```
git clone https://github.com/jrief/django-formset.git
cd django-formset
python -m venv .venv
source .venv/bin/activate
pip install -r testapp/requirements.txt
pip install --no-deps -e .
npm install --also=dev
npm run tag-attributes
npm run tailwindcss
npm run build
testapp/manage.py migrate
testapp/manage.py runserver
```

Instead, based on the test.yml file, I had to use the following commands to get the test site to run:

```
git clone https://github.com/jrief/django-formset.git
cd django-formset
python3 -m venv .venv
source .venv/bin/activate
pip install "Django==4.1.*"
pip install -r testapp/requirements.txt
pip install --no-deps -e .
npm install --include=dev
npm run tag-attributes
npm run tailwindcss
npm run esbuild
npm run compilescss
mkdir workdir
testapp/manage.py migrate
testapp/manage.py runserver
```

This also doesn't seem to install bootstrap in the test app, so I get the following warnings from the devel server:
```
WARNING: Not Found: /static/node_modules/bootstrap/dist/css/bootstrap.min.css
WARNING: "GET /static/node_modules/bootstrap/dist/css/bootstrap.min.css HTTP/1.1" 404 179
```

**Comment by jrief** [comment]
> python3 -m venv .venv

this depends on which OS/configuration you're working. Nowadays, Python-3 should be the the default everywhere.

I added Django==4.1.* to the install instructions.

> This also doesn't seem to install bootstrap in the test app, so I get the following warnings from the devel server

Weird. According to `package.json`, Bootstrap should be installed by `npm`. Did you configure your `settings.py` to use:

```python
STATICFILES_DIRS = [
    ('node_modules', BASE_DIR / 'node_modules'),
]
```

**Comment by agseaton** [comment]
Yes, the main things were needing to install django, replacing `npm run build` with `npm run esbuild`, and creating the workdir directory.

I have not modified `settings.py`, I'm just running these instructions verbatim. So I think the issue is that while `npm` does install bootstrap as per `package.json`, it puts it in `django-formset/node_modules` whereas the testapp is configured to look at `django-formset/testapp/node_modules`.

**Comment by agseaton** [comment]
Actually, I realised I'm wrong about why bootstrap it isn't working. Let me dig into this a bit more...

**Comment by agseaton** [comment]
Okay. I think I figured it out. Apologies for the confusion -- I am new to `django` so I'm still getting to grips with everything.

After looking more closely at `settings.py`, I think the configuration is fine. The issue is that the environment variable `DJANGO_DEBUG` was not set to true, so the `staticfiles` app wasn't automatically serving static files for `testapp`. So, including what you mentioned about `python` vs `python3`, the changes to the documentation should be something like:

```diff
        source .venv/bin/activate
        pip install -r testapp/requirements.txt
        pip install --no-deps -e .
-       npm install --also=dev
+       npm install --include=dev
        npm run tag-attributes
        npm run tailwindcss
-       npm run build
+       npm run esbuild
+       npm run compilescss
+       export DJANGO_DEBUG=true
        testapp/manage.py migrate
        testapp/manage.py runserver
```

**Comment by agseaton** [comment]
Great, looks like it is fixed now.
