### ISSUE TITLE
RichTextarea overflows

### ISSUE THREAD

**Issue by Actionb** [jrief/django-formset#59]
Content flows out of the bottom of the textarea. 

![richtext_overflow](https://user-images.githubusercontent.com/10028803/235091560-8aa3ca30-f0a3-4ec6-afab-e9cd1a4b4ae5.png)

**Comment by jrief** [comment]
Hmmm,
did you somehow modify the CSS?
Which CSS framework are you using, it looks like Bootstrap.
The element `<div contenteditable="true" class="ProseMirror">…</div>` should have `overflow-y: auto;`. Do you see that in your developer tools?

**Comment by Actionb** [comment]
No I haven't modified the CSS. 

Only the Foundation framework has overflow for the `ProseMirror` set to auto: https://django-formset.fly.dev/foundation/advertisementform

The rest have overflow set to `visible`.

**Comment by jrief** [comment]
Please check this demo: https://django-formset.fly.dev/foundation/advertisement

there is an issue with positioning, `top` should be ~`40px` but it currently is `109px`. Don't know why.

**Comment by Actionb** [comment]
This is what that looks like for me:   

![Screenshot 2023-06-19 at 14-27-27 Django-Formset Demo](https://github.com/jrief/django-formset/assets/10028803/7382e9ac-b0a4-4b87-87f7-9ab882724cdd)

I see you fixed the issue with the overflow, but I'm not quite sure what you want me to look at in regards to the positioning. Do you even need absolute positioning here?
