### ISSUE TITLE
Uncaught error when using MultiWidget

### ISSUE THREAD

**Issue by Actionb** [jrief/django-formset#61]
When using a MultiValueField with a MultiWidget widget, `assertUniqueName` in `DjangoFormset.ts` throws an error:
`Uncaught Error: Duplicate name 'phone_number_0' on multiple input fields on 'phone_number_1'`

Example: https://github.com/Actionb/django-formset/commit/6555d75448c78b7c50de316ea6fb979999b67fe6

**Comment by jrief** [comment]
Did you check the rendered HTML? Each field must have a unique name, otherwise the code responsible for building the submission payload can't (for obvious reasons) work. 

Btw. I am planning to create a phone-number widget similar to that of Google in version 1.1 or 1.2.

**Comment by jrief** [comment]
could you please paste the form using that widget. I will add that to the tests and/or demo.

btw. have you been able to test #57 ? Should imo be fixed.

**Comment by Actionb** [comment]
>could you please paste the form using that widget. I will add that to the tests and/or demo.

The form:
> Example: [Actionb@6555d75](https://github.com/Actionb/django-formset/commit/6555d75448c78b7c50de316ea6fb979999b67fe6)
----
> btw. have you been able to test https://github.com/jrief/django-formset/issues/57 ? Should imo be fixed.

I haven't gotten around to it yet. I will check it out next week.

**Comment by jrief** [comment]
Can you please try again with version 1.0. 

This example https://django-formset.fly.dev/model-collections/#one-to-many-relations seems to be the closest from what you describe. There all names are unique together with their parent model object.

**Comment by Actionb** [comment]
I still get the same error:
```
Uncaught Error: Duplicate name 'phone_number_0' on multiple input fields on 'phone_number_1'
    assertUniqueName http://127.0.0.1:8000/static/formset/js/django-formset.js:25
    Gt http://127.0.0.1:8000/static/formset/js/django-formset.js:25
    assignFieldsToForms http://127.0.0.1:8000/static/formset/js/django-formset.js:25
    connectedCallback http://127.0.0.1:8000/static/formset/js/django-formset.js:25
    connectedCallback http://127.0.0.1:8000/static/formset/js/django-formset.js:25
    <anonymous> http://127.0.0.1:8000/static/formset/js/django-formset.js:25
    promise callback* http://127.0.0.1:8000/static/formset/js/django-formset.js:25
    EventListener.handleEvent* http://127.0.0.1:8000/static/formset/js/django-formset.js:25
django-formset.js:25:3447

````

This doesn't have anything to do with unique togethers or relations (was your comment meant for some other issue perhaps?). 

I believe the issue is that `assertUniqueName` is checking the wrong thing. Contrary to its name, it is throwing an exception when the names of the input fields in a field group are **not** unique, i.e. when they do **not** share the same name.
  I suppose none of the forms you have worked with had formfields that produce multiple inputs (such as MultiValueField + MultiWidget), so there was never more than one element in a field group and the assertion could never fail.

**Comment by codematsing** [comment]
Hello, still existing in current develop version

replicated version:  98384e8336fb747abc41c64ebcccb743c12e35b6

![Image](https://github.com/user-attachments/assets/0c4cc008-0e59-4949-802c-431880c2cb36)

**Comment by codematsing** [comment]
Hello, still existing in current develop version

replicated version:  98384e8336fb747abc41c64ebcccb743c12e35b6
test view: http://127.0.0.1:8000/bootstrap/multiwidget

![Image](https://github.com/user-attachments/assets/0c4cc008-0e59-4949-802c-431880c2cb36)

**Additional Observation:**

* if the multiwidget has multiple subwidgets which inherit `forms.widgets.Input`, the uncaught error shows
* however, if the multiwidget has multiple subwidgets which inherit `forms.widgets.ChoiceWidget`, there is no uncaught error. My assumption is that it has something to do with some indexing happening in `forms.widgets.ChoiceWidget`

**Suggested Fix**

(Please note that I'm not fully sure about this as I'm just learning typescript as I go along with understanding django-formset.ts, but I tried to relate this to I guess the previous commit diff: https://github.com/jrief/django-formset/commit/568ed5f01d6f1b865ddd294bdcbdbbae7143854d

``` js
	private assertUniqueName(): string {
		let seen = new Set<string>(); // Stores names to check for duplicates
		let name = '__undefined__';

		for (const element of this.fieldElements) {
			if (seen.has(element.name)) {
				throw new Error(`Duplicate name '${element.name}' found on multiple input fields.`);
			}
			seen.add(element.name);

			// Set the first valid name
			if (name === '__undefined__') {
				name = element.name;
			}
		}

		return name;
	}
```
