### ISSUE TITLE
submit and reset button not working

### ISSUE THREAD

**Issue by sasikumar1978k** [jrief/django-formset#77]
submit and reset button not working. but it was working earlier

**Comment by jrief** [comment]
> but it was working earlier

what do you mean by that? Did you read the Changelog for version 1?

**Comment by sasikumar1978k** [comment]
NO

**Comment by jrief** [comment]
Please describe errors in a way, so that I can reproduce them. What does "NO" mean in this context?

**Comment by sasikumar1978k** [comment]
i don't know how to describe the error but submit and reset button was working earlier

**Comment by sasikumar1978k** [comment]
ok i have done it by changing click with df-click

**Comment by jrief** [comment]
It is always a good idea to read the Changelog before upgrading to a major version release.
