### ISSUE TITLE
selectize widget not working in modal

### ISSUE THREAD

**Issue by sasikumar1978k** [jrief/django-formset#78]
![Uploading Screenshot from 2023-06-29 15-23-10.png…]() widget not working in modal

**Comment by sasikumar1978k** [comment]
widget=Selectize widget not working in modal

![Screenshot from 2023-06-29 15-23-10](https://github.com/jrief/django-formset/assets/23027374/a311f3d0-09f5-4ac1-97ac-31320424047f)

**Comment by sasikumar1978k** [comment]
degree_type = forms.ChoiceField(
        choices=Degree_type,
        widget=Selectize(
            search_lookup='degree_type__icontains',
            placeholder="Select a Degree Type",
        ),
    
        required=True,
    )

**Comment by jrief** [comment]
Please read the [contribution guidelines on how to report bugs](https://django-formset.fly.dev/contributing/#reporting-bugs).
