### ISSUE TITLE
WARNING: "GET /static/formset/js/django-formset.js HTTP/1.1" 404 1843

### ISSUE THREAD

**Issue by codematsing** [jrief/django-formset#88]
Version: django-formset==1.0.1

similar case to #27, I followed instructions in https://django-formset.fly.dev/development/#developing-in-django-formset

Trying to reproduce issue reported in #28 since I am experiencing the same problem in my app. Wanted to investigate and follow the code for IncompleteSelectResponseMixin

Can't seem to find django-formset.js in static files or in anywhere in the repository, so I can't investigate.

I also tried to reverse it back to django-formset.min.js but it also can't find the file nor can I find the file in the repository

Hoping for some resolution. Thanks!

**Comment by jrief** [comment]
Did you install it from a wheel or using GitHub? If latter, you must compile the final JavaScript.
