### ISSUE TITLE
how to save data in FormCollectionView

### ISSUE THREAD

**Issue by MansourHaghgoo** [jrief/django-formset#9]
please help me. I can't save data in FormCollectionView

`class QuestionTrainingCreateView(LoginRequiredMixin, PermissionRequiredMixin, FormCollectionView):
    template_name = 'question_training/create.html'
    collection_class = ContactCollection
    success_url = '/path/to/success',`

**Comment by jrief** [comment]
I don't understand that question.

**Comment by MansourHaghgoo** [comment]
when using FormCollectionView class after submitting the form data is not saved in the database but the page redirect to success URL

models.py


class QuestionTraining(models.Model):
        ANSWER_CHOICES = (
            ('1', 'گزینه 1'),
            ('2', 'گزینه 2'),
            ('3', 'گزینه 3'),
            ('4', 'گزینه 4'),
        )
        device = models.ForeignKey(
            Device, on_delete=models.CASCADE, verbose_name='دستگاه')
        question = models.CharField(max_length=500, null=True)
        op1 = models.CharField(max_length=200, null=True)
        op2 = models.CharField(max_length=200, null=True)
        op3 = models.CharField(max_length=200, null=True)
        op4 = models.CharField(max_length=200, null=True)
        answer = models.CharField(max_length=1, choices=ANSWER_CHOICES, null=True)

    def __str__(self):
        return self.question


forms.py


class CreateQuestionTrainingDeviceForm(forms.ModelForm):

    class Meta:
        model = QuestionTraining

        fields = ['device']


class CreateQuestionTrainingForm(forms.ModelForm):

    class Meta:
        model = QuestionTraining

        fields = ['question', 'op1', 'op2', 'op3', 'op4', 'answer']


class QuestionCollection(FormCollection):
    min_siblings = 1
    max_siblings = 5
    extra_siblings = 1

    question = CreateQuestionTrainingForm()


class ContactCollection(FormCollection):

    divice = CreateQuestionTrainingDeviceForm()
    question = QuestionCollection()


views.py

class QuestionTrainingCreateView(LoginRequiredMixin, PermissionRequiredMixin,  FormCollectionView):
    redirect_field_name = 'redirect_to'
    permission_required = 'question_training.add_question_training'
    template_name = 'question_training/create.html'
    collection_class = ContactCollection

    def get_object(self, queryset=None):
        if self.extra_context['add'] is False:
            return super().get_object(queryset)

    def form_valid(self, form):
        if extra_data := self.get_extra_data():
            if extra_data.get('delete') is True:
                self.object.delete()
                success_url = self.get_success_url()
                response_data = {'success_url': force_str(
                    success_url)} if success_url else {}
                return JsonResponse(response_data)
        return super().form_valid(form)

**Comment by MansourHaghgoo** [comment]
I solved this problem with this code

```
    class QuizCreateView(FormCollectionView):

              template_name = 'create.html'
              collection_class = QuizCollection
              extra_context = None
                 
              def form_collection_valid(self, form_collection):
                  
                  form=form_collection.cleaned_data
          
                  for item in form["question"]:
                      device= form["device"]["device"]
                      question = item["question"]["question"]
                      op1 = item["question"]["op1"]
                      op2 = item["question"]["op2"]
                      op3 = item["question"]["op3"]
                      op4 = item["question"]["op4"]
                      answer = item["question"]["answer"]
                      reg = Quiz(device=device,question=question,op1=op1,op2=op2,op3=op3,op4=op4,answer=answer)
                      reg.save()
          
                  return JsonResponse({'success_url': self.get_success_url()})
```
I can not find a document for this class (EditCollectionView)

**Comment by jrief** [comment]
This [documentation](https://django-formset.readthedocs.io/en/latest/model-form.html) didn't help?

**Comment by MansourHaghgoo** [comment]
are you sure to use UpdateView class to edit data created by FormCollectionView?

**Comment by jrief** [comment]
Please check this demo which probably implements what you need:
https://django-formset.fly.dev/bootstrap/13-person

**Comment by codematsing** [comment]
@MansourHaghgoo thanks for this! Was trying to find documentation on saving the form collection and dove through the code as well. I can confirm that the appropriate method to override for `FormCollectionView` is form_collection_valid as oppose to form_valid in vanilla django

@jrief thank you for this amazing library and hoping for its continued success!

**Comment by lallulli** [comment]
Also for me it was not easy to find out the `form_collection_valid` method, because the documentation doesn't mention it. I would suggest to add a full example in the [Form Collections documentation page](https://django-formset.fly.dev/collections/).

Also, I am struggling to understand how to create model collection CRUDs using `EditCollectionView`, supporting add, update and delete operations. Completing the [documentation example](https://django-formset.fly.dev/model-collections/) with full urls and views would greatly help!

Thanks so much @jrief for your amazing library!

**Comment by jrief** [comment]
It's [documented here](https://django-formset.fly.dev/model-collections/) (scroll to end of page), although I agree that it is not immediately evident.

Thanks for reporting.
