### ISSUE TITLE
DatePicker Uncaught Error

### ISSUE THREAD

**Issue by codematsing** [jrief/django-formset#98]
version: 1.1.1

```
DateTimePicker-QJNPLAAA.js:1  Uncaught Error: Unknown aria-label on [object HTMLDivElement]
    at c.getViewMode (DateTimePicker-QJNPLAAA.js:1:8877)
    at c.registerElement (DateTimePicker-QJNPLAAA.js:1:14462)
    at MutationObserver.observe.childList (DateTimePicker-QJNPLAAA.js:1:8511)
```

What happens:
- popup of widget overlays entire page instead of date widget

**Comment by jrief** [comment]
Please use version 1.3.4

Does this [date-time-picker](https://django-formset.fly.dev/bootstrap/moment.picker) work for you?

Read the [contribution guidelines](https://django-formset.fly.dev/contributing/#reporting-bugs) before issuing a bug report.

**Comment by codematsing** [comment]
My bad, stopped trying to debug this since I found the workaround to use DateInput over DatePicker instead.

I did however replicated it using the instructions in your documentation.

The issue seems to arise when we use DatePicker on FormCollections

## Reproduction Steps:

```python
# forms/birthdate.py
class BirthdateFormCollection(FormCollection):
    birth_date_forms = BirthdatePickerForm()
    min_siblings=2
```

```python
# testapp/views.py
    path('birthdate.picker.formcollection', DemoFormCollectionView.as_view(
        collection_class=BirthdateFormCollection,
    ), name='birthdate.picker.formcollection'),
```
## Screenshot
![image](https://github.com/jrief/django-formset/assets/83852662/6271cf1c-edfb-421a-b7ea-fbedd3f9d797)

test on: http://localhost:8000/bootstrap/birthdate.picker.formcollection

**Comment by jrief** [comment]
That's indeed a weird modal dialog. Can you please share the complete code to reproduce it. Just point me on your GitHub repository branch.

**Comment by tolland** [comment]
![js_error_aria_label_2024-09-07_09-58](https://github.com/user-attachments/assets/9364b2ed-648e-4d0e-b16e-9dba1f6f2e78)

**Comment by codematsing** [comment]
Just to note my issue here is that I forgot to include the CalendarResponseMixin in the FormView which causes the error
